package ru.mgusev.eldritchhorror.database.staticDB.migrations;

import android.arch.persistence.db.SupportSQLiteDatabase;
import android.arch.persistence.room.migration.Migration;

public class StaticDBMigration8to9 {

    public static final Migration MIGRATION_8_9 = new Migration(8, 9) {
        @Override
        public void migrate(SupportSQLiteDatabase database) {
            database.execSQL("CREATE TABLE `cards` (`_id` INTEGER NOT NULL, `name_resource_id` TEXT, `type_id` INTEGER NOT NULL, PRIMARY KEY(`_id`))");
            database.execSQL("INSERT INTO cards (\n" +
                    "                      type_id,\n" +
                    "                      name_resource_id,\n" +
                    "                      _id\n" +
                    "                  )\n" +
                    "                  VALUES (\n" +
                    "                      4,\n" +
                    "                      'agreement',\n" +
                    "                      1\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      8,\n" +
                    "                      'amnesia',\n" +
                    "                      2\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'attuned',\n" +
                    "                      3\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      7,\n" +
                    "                      'back_injury',\n" +
                    "                      4\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      2,\n" +
                    "                      'blessed',\n" +
                    "                      5\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      1,\n" +
                    "                      'blight',\n" +
                    "                      6\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      2,\n" +
                    "                      'composed',\n" +
                    "                      7\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      1,\n" +
                    "                      'corruption',\n" +
                    "                      8\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      1,\n" +
                    "                      'cursed',\n" +
                    "                      9\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      4,\n" +
                    "                      'dark_pact',\n" +
                    "                      10\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      3,\n" +
                    "                      'debt',\n" +
                    "                      11\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      8,\n" +
                    "                      'despair',\n" +
                    "                      12\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      10,\n" +
                    "                      'detained',\n" +
                    "                      13\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      6,\n" +
                    "                      'diseased',\n" +
                    "                      14\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'elusive',\n" +
                    "                      15\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      4,\n" +
                    "                      'funding',\n" +
                    "                      16\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'guts',\n" +
                    "                      17\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      8,\n" +
                    "                      'hallucinations',\n" +
                    "                      18\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      1,\n" +
                    "                      'haunted',\n" +
                    "                      19\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      7,\n" +
                    "                      'head_injury',\n" +
                    "                      20\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'headstrong',\n" +
                    "                      21\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      8,\n" +
                    "                      'hunger',\n" +
                    "                      22\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      9,\n" +
                    "                      'hunted',\n" +
                    "                      23\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      5,\n" +
                    "                      'hypothermia',\n" +
                    "                      24\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      6,\n" +
                    "                      'infection',\n" +
                    "                      25\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      7,\n" +
                    "                      'internal_injury',\n" +
                    "                      26\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      7,\n" +
                    "                      'leg_injury',\n" +
                    "                      27\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      2,\n" +
                    "                      'living_link',\n" +
                    "                      28\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      10,\n" +
                    "                      'lost_in_time_and_space',\n" +
                    "                      29\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'martial_prowess',\n" +
                    "                      30\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'meditation',\n" +
                    "                      31\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'moxie',\n" +
                    "                      32\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      8,\n" +
                    "                      'paranoia',\n" +
                    "                      33\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'perceptive',\n" +
                    "                      34\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      6,\n" +
                    "                      'poisoned',\n" +
                    "                      35\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'practiced',\n" +
                    "                      36\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      4,\n" +
                    "                      'promise_of_power',\n" +
                    "                      37\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'quick_study',\n" +
                    "                      38\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'relentless',\n" +
                    "                      39\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'resilient',\n" +
                    "                      40\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      2,\n" +
                    "                      'righteous',\n" +
                    "                      41\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'rugged',\n" +
                    "                      42\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'silver_tongued',\n" +
                    "                      43\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'skulduggery',\n" +
                    "                      44\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'studious',\n" +
                    "                      45\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      8,\n" +
                    "                      'terror',\n" +
                    "                      46\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'visions',\n" +
                    "                      47\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      9,\n" +
                    "                      'wanted',\n" +
                    "                      48\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      4,\n" +
                    "                      'debt',\n" +
                    "                      49\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      11,\n" +
                    "                      'composed',\n" +
                    "                      50\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      12,\n" +
                    "                      'alter_fate',\n" +
                    "                      51\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      13,\n" +
                    "                      'arcane_insight',\n" +
                    "                      52\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      12,\n" +
                    "                      'astral_travel',\n" +
                    "                      53\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      12,\n" +
                    "                      'azure_flame',\n" +
                    "                      54\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      13,\n" +
                    "                      'banishment',\n" +
                    "                      55\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      12,\n" +
                    "                      'beast_within',\n" +
                    "                      56\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      14,\n" +
                    "                      'binding',\n" +
                    "                      57\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      13,\n" +
                    "                      'blessing_of_isis',\n" +
                    "                      58\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      13,\n" +
                    "                      'call_the_storm',\n" +
                    "                      59\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      14,\n" +
                    "                      'clairvoyance',\n" +
                    "                      60\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      13,\n" +
                    "                      'conjuration',\n" +
                    "                      61\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      14,\n" +
                    "                      'dread_curse',\n" +
                    "                      62\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      12,\n" +
                    "                      'enchant_weapon',\n" +
                    "                      63\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      12,\n" +
                    "                      'enchanting_grace',\n" +
                    "                      64\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      13,\n" +
                    "                      'feed_the_mind',\n" +
                    "                      65\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      12,\n" +
                    "                      'find_gate',\n" +
                    "                      66\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      14,\n" +
                    "                      'flesh_ward',\n" +
                    "                      67\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      12,\n" +
                    "                      'forced_learning',\n" +
                    "                      68\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      14,\n" +
                    "                      'healing_words',\n" +
                    "                      69\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      14,\n" +
                    "                      'instill_bravery',\n" +
                    "                      70\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      14,\n" +
                    "                      'intervene',\n" +
                    "                      71\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      12,\n" +
                    "                      'markings_of_isis',\n" +
                    "                      72\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      12,\n" +
                    "                      'minds_eye',\n" +
                    "                      73\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      14,\n" +
                    "                      'mists_of_releh',\n" +
                    "                      74\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      13,\n" +
                    "                      'occult_exaltation',\n" +
                    "                      75\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      13,\n" +
                    "                      'plumb_the_void',\n" +
                    "                      76\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      13,\n" +
                    "                      'poison_mist',\n" +
                    "                      77\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      13,\n" +
                    "                      'shriveling',\n" +
                    "                      78\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      12,\n" +
                    "                      'shroud_of_shadow',\n" +
                    "                      79\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      14,\n" +
                    "                      'spectral_razor',\n" +
                    "                      80\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      14,\n" +
                    "                      'storm_of_spirits',\n" +
                    "                      81\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      13,\n" +
                    "                      'summon_byakhee',\n" +
                    "                      82\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      13,\n" +
                    "                      'summoning',\n" +
                    "                      83\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      12,\n" +
                    "                      'voice_of_ra',\n" +
                    "                      84\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      14,\n" +
                    "                      'wither',\n" +
                    "                      85\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      14,\n" +
                    "                      'wrack',\n" +
                    "                      86\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'funding_the_cause',\n" +
                    "                      87\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'for_the_greater_good',\n" +
                    "                      88\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'enlist_the_masses',\n" +
                    "                      89\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'exploring_the_ruins',\n" +
                    "                      90\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'courier_run',\n" +
                    "                      91\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'bury_them_deep',\n" +
                    "                      92\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'dimensional_study',\n" +
                    "                      93\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'purifying_the_world',\n" +
                    "                      94\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'prayer',\n" +
                    "                      95\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'invoke_the_elements',\n" +
                    "                      96\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'light_of_reason',\n" +
                    "                      97\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'know_thy_enemy',\n" +
                    "                      98\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'mastering_the_art',\n" +
                    "                      99\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'seeking_the_masters',\n" +
                    "                      100\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'push_it_to_the_limit',\n" +
                    "                      101\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'sacrifices_to_make',\n" +
                    "                      102\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'sealing_the_old_ones',\n" +
                    "                      103\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'tempted_by_darkness',\n" +
                    "                      104\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'walking_the_ley_lines',\n" +
                    "                      105\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'unspeakable_research',\n" +
                    "                      106\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'turning_the_tide',\n" +
                    "                      107\n" +
                    "                  ),\n" +
                    "                  (\n" +
                    "                      15,\n" +
                    "                      'wave_of_destruction',\n" +
                    "                      108\n" +
                    "                  );\n");

            database.execSQL("CREATE TABLE `cards_type` (`_id` INTEGER NOT NULL, `name_resource_id` TEXT, `category_resource_id` TEXT, PRIMARY KEY(`_id`))");
            database.execSQL("INSERT INTO card_types (\n" +
                    "                           category_resource_id,\n" +
                    "                           name_resource_id,\n" +
                    "                           _id\n" +
                    "                       )\n" +
                    "                       VALUES (\n" +
                    "                           'condition',\n" +
                    "                           'bane',\n" +
                    "                           1\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'condition',\n" +
                    "                           'boon',\n" +
                    "                           2\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'condition',\n" +
                    "                           'common',\n" +
                    "                           3\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'condition',\n" +
                    "                           'deal',\n" +
                    "                           4\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'condition',\n" +
                    "                           'exposure',\n" +
                    "                           5\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'condition',\n" +
                    "                           'illness',\n" +
                    "                           6\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'condition',\n" +
                    "                           'injury',\n" +
                    "                           7\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'condition',\n" +
                    "                           'madness',\n" +
                    "                           8\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'condition',\n" +
                    "                           'pursuit',\n" +
                    "                           9\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'condition',\n" +
                    "                           'restriction',\n" +
                    "                           10\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'condition',\n" +
                    "                           'talent',\n" +
                    "                           11\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'spell',\n" +
                    "                           'glamour',\n" +
                    "                           12\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'spell',\n" +
                    "                           'ritual',\n" +
                    "                           13\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'spell',\n" +
                    "                           'incantation',\n" +
                    "                           14\n" +
                    "                       ),\n" +
                    "                       (\n" +
                    "                           'unique_asset',\n" +
                    "                           'task',\n" +
                    "                           15\n" +
                    "                       );\n");

            database.execSQL("CREATE TABLE `cards_expansions` (`card_id` INTEGER NOT NULL, `expansion_id` INTEGER NOT NULL, PRIMARY KEY(`card_id`, `expansion_id`))");
            database.execSQL("INSERT INTO cards_expansions (\n" +
                    "                                 expansion_id,\n" +
                    "                                 card_id\n" +
                    "                             )\n" +
                    "                             VALUES (\n" +
                    "                                 4,\n" +
                    "                                 1\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 2\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 8,\n" +
                    "                                 3\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 4\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 5\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 6\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 7\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 9,\n" +
                    "                                 8\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 9\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 10\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 11\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 5,\n" +
                    "                                 12\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 13\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 5,\n" +
                    "                                 14\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 15\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 16\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 8,\n" +
                    "                                 17\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 18\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 5,\n" +
                    "                                 19\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 4,\n" +
                    "                                 20\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 21\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 22\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 23\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 24\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 25\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 26\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 27\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 9,\n" +
                    "                                 28\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 2,\n" +
                    "                                 29\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 30\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 9,\n" +
                    "                                 31\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 32\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 33\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 9,\n" +
                    "                                 34\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 2,\n" +
                    "                                 35\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 8,\n" +
                    "                                 36\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 37\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 38\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 8,\n" +
                    "                                 39\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 40\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 4,\n" +
                    "                                 41\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 8,\n" +
                    "                                 42\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 9,\n" +
                    "                                 43\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 44\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 45\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 8,\n" +
                    "                                 46\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 47\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 48\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 49\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 50\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 29\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 30\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 15\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 9,\n" +
                    "                                 36\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 5,\n" +
                    "                                 51\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 52\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 4,\n" +
                    "                                 53\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 4,\n" +
                    "                                 54\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 55\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 8,\n" +
                    "                                 56\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 57\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 58\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 9,\n" +
                    "                                 59\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 60\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 61\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 62\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 5,\n" +
                    "                                 63\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 5,\n" +
                    "                                 64\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 65\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 66\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 67\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 5,\n" +
                    "                                 68\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 2,\n" +
                    "                                 69\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 70\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 71\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 4,\n" +
                    "                                 72\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 73\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 74\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 8,\n" +
                    "                                 75\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 76\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 2,\n" +
                    "                                 77\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 78\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 5,\n" +
                    "                                 79\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 8,\n" +
                    "                                 80\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 81\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 82\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 83\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 4,\n" +
                    "                                 84\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 1,\n" +
                    "                                 85\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 5,\n" +
                    "                                 86\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 87\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 88\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 89\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 4,\n" +
                    "                                 90\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 91\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 92\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 93\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 94\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 4,\n" +
                    "                                 95\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 5,\n" +
                    "                                 96\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 8,\n" +
                    "                                 97\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 5,\n" +
                    "                                 98\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 99\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 8,\n" +
                    "                                 100\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 9,\n" +
                    "                                 101\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 102\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 103\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 9,\n" +
                    "                                 104\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 3,\n" +
                    "                                 105\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 106\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 6,\n" +
                    "                                 107\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 8,\n" +
                    "                                 108\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 7,\n" +
                    "                                 105\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 4,\n" +
                    "                                 103\n" +
                    "                             ),\n" +
                    "                             (\n" +
                    "                                 5,\n" +
                    "                                 94\n" +
                    "                             );\n");
        }
    };
}